version: '2'

services:
  web-service:
    container_name: web-service
    build: .
    image: web-service:1.0
    ports:
      - "3000:3000"
      - "5432:5432"
    environment:
      - APP_NAME=github
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSRGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 1234

  adminer:
    image: adminer
    restart: always
    ports:
      - 5432:5432


